<?xml version="1.0"?>
<package format="3">
  <name>swarm_core</name>
  <version>0.2.0</version>
  <description>Production Decentralized Drone Swarm Core Nodes &amp; Action Servers</description>
  <maintainer email="hiteshrane28@gmail.com">dynam</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>std_msgs</depend>
  <depend>px4_msgs</depend>
  <depend>swarm_interfaces</depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
